### ISSUE TITLE
Supporting: Docker 1.10 & Compose 1.6 updates

### ISSUE THREAD

**Issue by andrewmclagan** [tutumcloud/haproxy#157] opened 2016-02-10 00:11 UTC
Im aware that its only a very recent release [4th February] although is their a roadmap for supporting docker-compose syntax version 2? Specifically regarding the changes to networking and links in docker 1.10?

Looking forward to using these features :-)

**Comment by refextu** [comment] 2016-02-10 09:21
+1

**Comment by greeninja** [comment] 2016-02-15 09:30
+1

**Comment by nunovieira** [comment] 2016-02-17 10:34
+1

**Comment by otbe** [comment] 2016-02-17 18:53
+1

**Comment by MBuffenoir** [comment] 2016-02-19 05:07
+1 
Subsidiary: it looks like this repo is now a duplicate of https://github.com/docker/dockercloud-haproxy ... which one should we use ?

**Comment by andrewmclagan** [comment] 2016-02-19 05:42
hmm... It seems there is about to be a re-branding? Im seeing a number of repos replicated under the docker github account :-)

* https://github.com/tutumcloud
* https://github.com/docker?utf8=%E2%9C%93&query=cloud

Well we know that Docker bought Tutum not so long ago. Perhaps thats the move, a rebrand under the Docker banner as Docker Cloud?

**Comment by andrewmclagan** [comment] 2016-02-19 05:43
oh wow... https://docs.docker.com/docker-cloud/faq/what-is-cloud/

**Comment by fermayo** [comment] 2016-02-19 09:47
This image (`tutum/haproxy`) will be deprecated in favour of `dockercloud/haproxy` (https://github.com/docker/dockercloud-haproxy)

At the moment, both images work with any version of Compose, as long as containers are linked to each other on the default `bridge` network, which is the one that is keeping "legacy links" (with propagated env vars) which are used by both images.

We will be updating `dockercloud/haproxy` to support local containers attached to 1.10 networks, and also to autoconfigure itself if it has access to docker/swarm events.

**Comment by andrewmclagan** [comment] 2016-02-19 15:13
After reviewing the pricing structure of Docker Cloud, i'd strongly recommend anyone to steer clear. For our current project Dock Cloud would see our infrastructure costs rise just over 300%. 

Very surprised by their choice in pricing. Our finance team crunched the numbers and within less then 6 months it would be more economic to roll our own deployment pipeline on swarm and compose. That we will now do, as its only an upfront cost. Not on going.

**Comment by fermayo** [comment] 2016-02-19 15:24
@andrewmclagan We are going to make `dockercloud/haproxy` work locally with Docker 1.10+ and Compose v2 format as well as in Docker Cloud. So it will be useful regardless of whether you use Docker Cloud or not. You can send your feedback regarding pricing in our forums: https://forums.docker.com/c/docker-cloud

**Comment by andrewmclagan** [comment] 2016-02-19 15:32
Already have .. sad face :-(

**Comment by tifayuki** [comment] 2016-03-11 10:47
This is done in `dockercloud/haproxy:1.2`

**Closed by tifayuki** 2016-03-11 10:47 UTC
